version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains aribnb listings.
    columns:
      - name: listing_id
        description: primary key for listing table
        tests:
          - not_null
          - unique
        data_type: number
      - name: listing_name
        data_type: varchar
      - name: room_type
        data_type: varchar
      - name: minimum_nights
        description: |-
          Minimum number of nights required to rent this property.
          Keep in mind that old listings might have `minimum_nights` set
          to 0 in the source tables. Our cleansing algorithm updates this to `1`.
        data_type: number
      - name: host_id
        data_type: number
      - name: price
        data_type: number
      - name: created_at
        data_type: timestamp_ntz
      - name: updated_at
        data_type: timestamp_ntz
  - name: host_id
    description: primary key for host table
    tests:
      - not_null
      - relationships:
          to: ref('dim_hosts_cleansed')
          field: host_id
  - name: room_type
    description: type of apartment / room
    tests:
      - accepted_values:
          values: [ 'Entire home/apt', 'Private room', 'Shared room', 'Hotel room' ]

  - name: minimum_nights
    description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
    tests:
      - positive_value
